Repository Nexters/8potatoes-client, pull requests merged in 2024-08, with the labels that each got.

#4 [SETTING] 변경된 디자인 시안에 맞춰 Color Token 수정
  src/styles/color.ts
Labels: ⚙ Setting

#5 [FEAT] Drawer 공용 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/drawer/Drawer.style.tsx
  src/components/drawer/Drawer.tsx
  src/components/drawer/DrawerClose.tsx
  src/components/drawer/DrawerContent.tsx
  src/components/drawer/DrawerTrigger.tsx
  src/components/drawer/index.ts
  src/hooks/useDisclosure.ts
Labels: ✨ Feature

#8 [FEAT] 공용 컴포넌트 Text 추가
  src/components/text/Text.style.tsx
  src/components/text/Text.tsx
  src/components/text/index.ts
  src/styles/color.ts
  src/styles/font.ts
  src/styles/theme.ts
Labels: ✨ Feature

#9 [FEAT] 휴게소 목록을 보여주는 Drawer 컴포넌트 개발
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/icons/folk-spoon.svg
  src/assets/icons/marker-flag.svg
  src/assets/icons/star.svg
  src/components/drawer/Drawer.style.tsx
  src/components/drawer/Drawer.tsx
  src/components/drawer/DrawerContent.tsx
  src/components/flex-box/FlexBox.style.tsx
  src/components/flex-box/FlexBox.tsx
  src/components/flex-box/index.ts
  src/components/text/Text.style.tsx
  src/components/uncontrolled-drawer/UnControlledDrawer.style.tsx
  src/components/uncontrolled-drawer/UnControlledDrawer.tsx
  src/components/uncontrolled-drawer/UnControlledDrawerContent.tsx
  src/components/uncontrolled-drawer/index.ts
  src/features/rest-area/rest-area-drawer/RestAreaDrawer.style.tsx
  src/features/rest-area/rest-area-drawer/RestAreaDrawer.tsx
  src/features/rest-area/rest-area-drawer/index.ts
  src/features/rest-area/rest-area-information/RestAreaInformation.style.tsx
  src/features/rest-area/rest-area-information/RestAreaInformation.tsx
  src/features/rest-area/rest-area-information/index.ts
  src/utils/dayjs.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: 🔨 Refactor, ✨ Feature

#13 [FEAT] 주유 및 주차 정보 페이지 구현
  src/features/rest-area/rest-area-fuel-information/RestAreaFuelInformation.style.tsx
  src/features/rest-area/rest-area-fuel-information/RestAreaFuelInformation.tsx
  src/features/rest-area/rest-area-fuel-information/index.ts
  src/features/rest-area/rest-area-parking-information/RestAreaParkingInformation.style.tsx
  src/features/rest-area/rest-area-parking-information/RestAreaParkingInformation.tsx
  src/features/rest-area/rest-area-parking-information/index.ts
  src/pages/rest-area-fuel/RestAreaFuelPage.style.tsx
  src/pages/rest-area-fuel/RestAreaFuelPage.tsx
  src/pages/rest-area-fuel/index.ts
  src/styles/global.tsx
Labels: 🧑‍🎨 Style, ✨ Feature

#11 [FEAT] 기타 정보 페이지 구현
  src/App.tsx
  src/assets/icons/call.svg
  src/assets/icons/copy.svg
  src/features/rest-area/rest-area-other-information/RestAreaOtherInformation.style.ts
  src/features/rest-area/rest-area-other-information/RestAreaOtherInformation.tsx
  src/features/rest-area/rest-area-other-information/index.ts
  src/styles/global.tsx
  src/utils/common.ts
Labels: 🧑‍🎨 Style, ✨ Feature

#10 [FEAT] 출발, 도착 및 휴게소 마커와 경로를 지도에 그리는 기능 추가
  .env.template
  .gitignore
  src/apis/api.ts
  src/apis/tmap/index.ts
  src/apis/tmap/type.ts
  src/assets/icons/arrow-right.svg
  src/assets/icons/bubble-end-text.svg
  src/assets/icons/bubble-start-text.svg
  src/assets/icons/destination-marker.svg
  src/assets/icons/marker-flag.svg
  src/components/drawer/Drawer.style.tsx
  src/components/drawer/DrawerContent.tsx
  src/components/uncontrolled-drawer/UnControlledDrawer.style.tsx
  src/components/uncontrolled-drawer/UnControlledDrawerContent.tsx
  src/constants/location.ts
  src/constants/query-key.ts
  src/features/location/route/Route.tsx
  src/features/location/search-box/SearchBox.tsx
  src/features/rest-area/destination-indicator/DestinationIndicator.style.tsx
  src/features/rest-area/destination-indicator/DestinationIndicator.tsx
  src/features/rest-area/destination-indicator/index.ts
  src/features/rest-area/destination-marker/DestinationMarker.style.tsx
  src/features/rest-area/destination-marker/DestinationMarker.tsx
  src/features/rest-area/destination-marker/index.ts
  src/features/rest-area/rest-area-bubble-marker/RestAreaBubbleMarker.style.tsx
  src/features/rest-area/rest-area-bubble-marker/RestAreaBubbleMarker.tsx
  src/features/rest-area/rest-area-bubble-marker/index.ts
  src/pages/rest-area-map/index.tsx
  src/query-hooks/location/query.ts
  src/routers/index.tsx
  src/types/location.ts
  tsconfig.app.json
Labels: ✨ Feature

#14 [FEAT] 휴게소 음식 상세 정보 페이지 개발
  src/assets/images/alternative-image.png
  src/features/rest-area/rest-area-detail-section/RestAreaDetailSection.style.tsx
  src/features/rest-area/rest-area-detail-section/RestAreaDetailSection.tsx
  src/features/rest-area/rest-area-detail-section/index.ts
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.constants.ts
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.style.tsx
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.tsx
  src/features/rest-area/rest-area-food-category/index.ts
  src/features/rest-area/rest-area-food-menu/RestAreaFoodMenu.style.tsx
  src/features/rest-area/rest-area-food-menu/RestAreaFoodMenu.tsx
  src/features/rest-area/rest-area-food-menu/index.ts
  src/hooks/useValidSearchParams.ts
  src/pages/rest-area-food/RestAreaFoodPage.style.tsx
  src/pages/rest-area-food/RestAreaFoodPage.tsx
  src/pages/rest-area-food/index.ts
  src/pages/rest-area-fuel/RestAreaFuelPage.style.tsx
Labels: 🧑‍🎨 Style, ✨ Feature

#15 [FEAT] 휴게소 목록 및 상세 정보 API 추가 및 Type 정의
  src/apis/api.ts
  src/apis/rest-area/index.ts
  src/apis/rest-area/type.ts
  src/apis/tmap/index.ts
  src/constants/query-key.ts
  src/query-hooks/location/query.ts
  src/query-hooks/rest-area/query.ts
  src/types/amenity.ts
  src/types/brand.ts
  src/types/menu.ts
  src/types/rest-area.ts
  src/types/restaurant.ts
Labels: ✨ Feature

#12 [FEAT] 상세 페이지 Tab Header 구현
  src/App.tsx
  src/assets/icons/dot.svg
  src/assets/icons/star.svg
  src/components/header/Header.tsx
  src/components/tab-header/TabHeader.style.ts
  src/components/tab-header/TabHeader.tsx
  src/components/tab-header/index.ts
  src/features/location/search/Search.tsx
  src/hooks/useIntersectionObserver.ts
  src/pages/templates/rest-area-detail/RestAreaDetail.tsx
  src/pages/templates/rest-area-detail/index.ts
  src/routers/index.tsx
  vite.config.ts
Labels: ✨ Feature

#17 [STYLE] 디자인 세부 스타일 반영
  src/assets/icons/reset-button.svg
  src/assets/icons/tooltip-arrow.svg
  src/components/drawer/Drawer.style.tsx
  src/components/drawer/DrawerContent.tsx
  src/components/tooltip/Tooltip.style.ts
  src/constants/z-index.ts
  src/features/location/current-location-search/CurrentLocationSearch.style.ts
  src/features/location/current-location-search/CurrentLocationSearch.tsx
  src/features/location/search-input/SearchInput.style.ts
  src/features/location/search/Search.tsx
  src/pages/location-search/LocationSearch.tsx
  src/query-hooks/location/query.ts
Labels: 🧑‍🎨 Style

#18 [FEAT] 기타 정보 및 주유/주차 정보 API 연동
  src/App.tsx
  src/apis/rest-area/index.ts
  src/apis/rest-area/type.ts
  src/apis/tmap/type.ts
  src/components/header/Header.tsx
  src/components/tab-header/TabHeader.tsx
  src/features/rest-area/rest-area-fuel-information/RestAreaFuelInformation.style.tsx
  src/features/rest-area/rest-area-fuel-information/RestAreaFuelInformation.tsx
  src/features/rest-area/rest-area-parking-information/RestAreaParkingInformation.style.tsx
  src/features/rest-area/rest-area-parking-information/RestAreaParkingInformation.tsx
  src/pages/rest-area-food/RestAreaFoodPage.style.tsx
  src/pages/rest-area-fuel/RestAreaFuelPage.style.tsx
  src/pages/rest-area-fuel/RestAreaFuelPage.tsx
  src/pages/rest-area-other-information/RestAreaOtherInformation.style.ts
  src/pages/rest-area-other-information/RestAreaOtherInformation.tsx
  src/pages/rest-area-other-information/index.ts
  src/pages/templates/rest-area-detail/RestAreaDetail.tsx
  src/query-hooks/rest-area/query.ts
  src/routers/index.tsx
  src/styles/color.ts
Labels: ✨ Feature

#16 [FEAT] 시작과 종료 지점을 기준으로 휴게소 목록을 반환하는 API 연동
  .env.template
  src/apis/rest-area/index.ts
  src/apis/tmap/type.ts
  src/components/drawer/Drawer.tsx
  src/components/flex-box/FlexBox.tsx
  src/components/uncontrolled-drawer/UnControlledDrawer.tsx
  src/constants/highway.ts
  src/features/rest-area/destination-marker/DestinationMarker.tsx
  src/features/rest-area/rest-area-bubble-marker/RestAreaBubbleMarker.style.tsx
  src/features/rest-area/rest-area-bubble-marker/RestAreaBubbleMarker.tsx
  src/features/rest-area/rest-area-drawer/RestAreaDrawer.tsx
  src/features/rest-area/rest-area-information/RestAreaInformation.style.tsx
  src/features/rest-area/rest-area-information/RestAreaInformation.tsx
  src/pages/rest-area-map/index.tsx
  src/query-hooks/location/query.ts
  src/query-hooks/rest-area/query.ts
  src/types/rest-area.ts
Labels: ✨ Feature

#21 [FIX] 고속도로 내 휴게소 목록을 가져오는 API 설계 변경에 맞춰 로직 수정
  src/apis/rest-area/index.ts
  src/apis/rest-area/type.ts
  src/constants/highway.ts
  src/constants/query-key.ts
  src/features/rest-area/rest-area-information/RestAreaInformation.style.tsx
  src/features/rest-area/rest-area-information/RestAreaInformation.tsx
  src/pages/rest-area-map/index.tsx
  src/query-hooks/location/query.ts
  src/query-hooks/location/util.ts
  src/query-hooks/rest-area/query.ts
Labels: 🐞 Bug

#19 [FEAT] 휴게소 메뉴 상세 페이지 API 연동
  src/apis/rest-area/index.ts
  src/apis/rest-area/type.ts
  src/constants/food-menu.ts
  src/features/rest-area/representative-menu-section/RepresentativeMenuSection.style.tsx
  src/features/rest-area/representative-menu-section/RepresentativeMenuSection.tsx
  src/features/rest-area/representative-menu-section/index.ts
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.constants.ts
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.style.tsx
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.tsx
  src/features/rest-area/rest-area-food-menu/RestAreaFoodMenu.tsx
  src/pages/rest-area-food/RestAreaFoodPage.style.tsx
  src/pages/rest-area-food/RestAreaFoodPage.tsx
  src/query-hooks/rest-area/query.ts
  src/routers/index.tsx
  src/types/menu.ts
  src/types/rest-area.ts
  tsconfig.app.json
Labels: ✨ Feature

#20 [FIX] Tabheader가 짧은 콘텐츠에서 min header로 고정되는 문제 해결
  src/components/tab-header/TabHeader.style.ts
  src/pages/templates/rest-area-detail/RestAreaDetail.style.tsx
  src/pages/templates/rest-area-detail/RestAreaDetail.tsx
Labels: 🐞 Bug

#22 [CHORE] 메인 페이지를 location-search 페이지로 바꾸기
  src/routers/index.tsx
Labels: ✨ Feature

#26 [FEAT] AsyncBoundary, Skeleton 공용 컴포넌트 개발
  src/components/async-boundary/AsyncBoundary.tsx
  src/components/async-boundary/index.ts
  src/components/skeleton/Skeleton.style.tsx
  src/components/skeleton/Skeleton.tsx
  src/components/skeleton/index.ts
Labels: ✨ Feature

#27 [FIX] Drawer 렌더링 시 Bounce 되는 현상 제거
  src/components/drawer/Drawer.style.tsx
  src/components/drawer/DrawerContent.tsx
  src/components/uncontrolled-drawer/UnControlledDrawer.style.tsx
  src/components/uncontrolled-drawer/UnControlledDrawerContent.tsx
Labels: 🐞 Bug

#23 [FEAT] 에셋 및 아이콘 설정
  .env.template
  index.html
  public/logo.png
  public/vite.svg
  src/assets/icons/amenities.svg
  src/assets/icons/asian-food.svg
  src/assets/icons/chinese-food.svg
  src/assets/icons/current-location.svg
  src/assets/icons/current-position.svg
  src/assets/icons/fueling-and-charging.svg
  src/assets/icons/korean-food.svg
  src/assets/icons/location-moving.svg
  src/assets/icons/location-pointer.svg
  src/assets/icons/menu.svg
  src/assets/icons/other-information.svg
  src/assets/icons/parking-space.svg
  src/assets/icons/recommendation-food.svg
  src/assets/icons/restaurant-time.svg
  src/assets/icons/snacks.svg
  src/assets/icons/store-brand.svg
  src/assets/icons/western-food.svg
  src/features/location/current-location-search/CurrentLocationSearch.style.ts
  src/features/location/current-location-search/CurrentLocationSearch.tsx
  src/features/location/location-select-field/LocationSelectField.tsx
  src/features/location/route/Route.style.ts
  src/features/location/route/Route.tsx
  src/features/location/search-tip/SearchTip.style.ts
  src/features/location/search-tip/SearchTip.tsx
  src/features/location/search/Search.tsx
  src/features/rest-area/rest-area-detail-section/RestAreaDetailSection.tsx
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.constants.ts
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.constants.tsx
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.style.tsx
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.tsx
  src/features/rest-area/rest-area-fuel-information/RestAreaFuelInformation.tsx
  src/features/rest-area/rest-area-parking-information/RestAreaParkingInformation.tsx
  src/pages/rest-area-food/RestAreaFoodPage.tsx
  src/pages/rest-area-other-information/RestAreaOtherInformation.tsx
Labels: ✨ Feature

#28 [FEAT] 404, 500 페이지 템플릿 및 에러 컴포넌트 추가
  src/components/async-boundary/AsyncBoundary.tsx
  src/components/error-box/ErrorBox.style.tsx
  src/components/error-box/ErrorBox.tsx
  src/components/error-box/index.ts
  src/pages/internal-error/InternalErrorPage.style.tsx
  src/pages/internal-error/InternalErrorPage.tsx
  src/pages/internal-error/index.ts
  src/pages/not-found/NotFoundPage.style.tsx
  src/pages/not-found/NotFoundPage.tsx
  src/pages/not-found/index.ts
  src/routers/index.tsx
Labels: ✨ Feature

#30 [FIX] baseURL 설정하는 방식으로 수정
  src/apis/tmap/index.ts
Labels: 🐞 Bug

#25 [DEPLOY] Github Action 기반의 정적 배포 Workflow 추가
  .github/workflows/development.yml
  .github/workflows/production.yml
  src/pages/rest-area-map/index.tsx
Labels: 🌏 Deploy

#31 [FIX] representative 레이아웃 및 애니메이션 수정
  src/features/rest-area/representative-menu-section/RepresentativeMenuSection.style.tsx
  src/features/rest-area/representative-menu-section/RepresentativeMenuSection.tsx
Labels: 🐞 Bug

#32 [CHORE] 아이콘 수정
  src/assets/icons/amenities.svg
  src/assets/icons/fueling-and-charging.svg
  src/assets/icons/marker-flag.svg
  src/assets/icons/menu.svg
  src/assets/icons/other-information.svg
  src/assets/icons/parking-space.svg
  src/assets/icons/restaurant-time.svg
  src/assets/icons/store-brand.svg
  src/assets/icons/western-food.svg
Labels: 🧑‍🎨 Style

#33 [FEAT] tab header 뒤로가기 및 destination indicator 클릭 로직 구현
  src/components/tab-header/TabHeader.tsx
  src/features/rest-area/destination-indicator/DestinationIndicator.tsx
  src/pages/location-search/LocationSearch.tsx
  src/pages/rest-area-map/index.tsx
Labels: ✨ Feature

#34 [FEAT] 휴게소 Empty 뷰 구현
  src/features/rest-area/rest-area-drawer/RestAreaDrawer.tsx
Labels: ✨ Feature

#35 feat: vite-open-graph-plugin 설치 및 서비스 OpenGraph 태그 적용
  index.html
  package.json
  pnpm-lock.yaml
  src/styles/global.tsx
  vite.config.ts
Labels: ✨ Feature

#36 [FEAT] Suspense view 생성
  src/components/tab-header/TabHeader.loading.tsx
  src/components/tab-header/TabHeader.tsx
  src/components/tab-header/index.ts
  src/features/rest-area/representative-menu-section/RepresentativeMenuSection.loading.tsx
  src/features/rest-area/representative-menu-section/index.ts
  src/features/rest-area/rest-area-drawer/RestAreaDrawer.tsx
  src/features/rest-area/rest-area-food-category/RestAreaFoodCategory.loading.tsx
  src/features/rest-area/rest-area-food-category/index.ts
  src/features/rest-area/rest-area-food-menu/RestAreaFoodMenu.loading.tsx
  src/features/rest-area/rest-area-food-menu/index.ts
  src/features/rest-area/rest-area-fuel-information/RestAreaFuelInformation.loading.tsx
  src/features/rest-area/rest-area-fuel-information/index.ts
  src/features/rest-area/rest-area-information/RestAreaInformation.loading.tsx
  src/features/rest-area/rest-area-information/RestAreaInformation.tsx
  src/features/rest-area/rest-area-information/index.ts
  src/features/rest-area/rest-area-parking-information/RestAreaParkingInformation.loading.tsx
  src/features/rest-area/rest-area-parking-information/index.ts
  src/pages/rest-area-food/RestAreaFoodPage.tsx
  src/pages/rest-area-fuel/RestAreaFuelPage.tsx
  src/pages/rest-area-other-information/RestAreaOtherInformation.loading.tsx
  src/pages/rest-area-other-information/RestAreaOtherInformation.style.ts
  src/pages/rest-area-other-information/index.ts
  src/pages/templates/rest-area-detail/RestAreaDetail.tsx
  src/routers/index.tsx
Labels: ✨ Feature
